ASPClient/Controllers/FileController.cs
using ASPClient.Models;
using Contract;
using Contract.ViewModel;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;

namespace ASPClient.Controllers
{
    public class FileController : Controller, ICallBack
    {
        public void Get(string state, bool flag = true)
        {
            var context = Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<GetHub>();
            context.Clients.All.displayMessage(state, flag);
        }
        // GET: File
        public JsonResult Index(string state = "", bool flag = false, string typeFolder = "")
        {


            ClientService clientService = new ClientService();
            List<AllFileType> json=null;
            clientService.OpenFile(this);
            //if (typeFolder == "delete")
            //{

            //}
            //else if (typeFolder == "SharedMe")
            //{

            //}
            //else if (typeFolder == "SharedUserMe")
            //{

            //}
            //else
            if (typeFolder == "Remove")
            {
                    json = clientService.FileProd.GetUserFileList(@"Trash\" + User.Identity.Name, state);
                    clientService.FileProd.Watcher(@"Trash\" + User.Identity.Name , state);   
            }
            else if(typeFolder == "MyFolder" || typeFolder=="")
            {
                if (state != "" && flag)
                {
                    json = clientService.FileProd.GetUserFileList("", state);
                    clientService.FileProd.Watcher("", state);
                }
                else
                {
                    json = clientService.FileProd.GetUserFileList(User.Identity.Name, state);
                    clientService.FileProd.Watcher(User.Identity.Name, state);
                }
            }
            return Json(json, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult AddDirectory(string name, string states)
        {
            ClientService clientService = new ClientService();
            clientService.OpenFile(this);
            if (states == "")
            {
                clientService.FileProd.AddDirectory(User.Identity.Name, User.Identity.Name, name);
            }
            else
            {
                clientService.FileProd.AddDirectory(User.Identity.Name, states, name);
            }
            return Json(states, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult ReName(string state, string oldName, string newName, string type)
        {
            ClientService clientService = new ClientService();
            clientService.OpenFile(this);
            clientService.FileProd.ReNameFile(state, oldName, newName, type);
            return Json(state, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult Delete(FileDelModel[] filAllDel)
        {
            ClientService clientService = new ClientService();
            clientService.OpenFile(this);
            clientService.FileProd.DeleteFile(filAllDel);
            return Json("", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteTrash(FileDelModel[] filAllDel)
        {
            ClientService clientService = new ClientService();
            clientService.OpenFile(this);
            clientService.FileProd.DeleteFileTrash(filAllDel,User.Identity.Name);
            return Json("", JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult RecoveryFile(FileDelModel[] filAllDel)
        {
            ClientService clientService = new ClientService();
            clientService.OpenFile(this);
            clientService.FileProd.RecoveryFileAndDirectory(filAllDel);
            return Json("", JsonRequestBehavior.AllowGet);
        }
        public FileResult GetFile(string name, string urlFile)
        {
            ClientService clientService = new ClientService();
            clientService.OpenFile(this);
            var file = clientService.FileProd.DownloadFile(urlFile);
            string fileType = "application/octet-stream";
            string fileName = name;


            return File(file, fileType, fileName);
        }
        [HttpPost]
        public JsonResult Upload()
        {
            ClientService clientService = new ClientService();
            clientService.OpenFile(this);
            foreach (string file in Request.Files)
            {
                var upload = Request.Files[file];
                var state = Request.Form["state"];
                if (state == "")
                {
                    state = User.Identity.Name;
                }
                if (upload != null)
                {
                    string fileName = System.IO.Path.GetFileName(upload.FileName);

                    using (var binaryReader = new BinaryReader(upload.InputStream))
                    {
                        clientService.FileProd.AddAndUpdateFile(User.Identity.Name,state, binaryReader.ReadBytes(upload.ContentLength), upload.FileName);
                    }

                }
            }
            return Json("файл загружен");
        }


    }
}

ASPClient/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ASPClient.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ASPClient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Cloud";
}
<style>
    tr{
        cursor:pointer;
    }
        tr:hover {
            background: #918C8C !important;
            color:#fff;
        }
</style>
<div class="col-md-12">
    <div class="panel">
        <div class="panel-body">
            <div class="col-md-12 padding-0" style="padding-bottom:20px;">
                <a href="#" class="btn uploadFile"><span class="icons icon-cloud-download"></span>Загрузить файл</a>
                <a href="#" class="btn addDirectory"><span class="fa fa-plus"></span>Добавить папку</a>
                <a href="#" class="btn removeAll"><span class="fa fa-remove"></span>Удалить</a>
                <a href="#" class="btn RecoveryAll" style="display: none;"><span class="fa fa-remove"></span>Восстановить</a>
            </div>
            <div class="responsive-table">
                <a href="#" style="font-size: 2em;" class="leftMenu" val=""><i class="fa fa-arrow-left"></i></a>
                <div class="menuName" style="float:right;"></div>
                <table class="table table-striped table-bordered" width="100%" cellspacing="0">
                    <!--thead>
                        <tr>
                            <th><input type="checkbox" class="icheck" name="checkbox1" /></th>
                            <th>Имя</th>
                            <th>Дата</th>
                            <th>Время</th>
                            <th>Размер</th>
                        </tr>
                    </thead-->
                    <tbody data-bind="foreach: allFile" class="allFiles">
                        <tr>
                            <td style=" width: 10px;"><span data-bind="if:Type == 'Папка'"><i class="fa fa-folder"></i></span><span data-bind="if:Type == 'Файл'"><i class="fa fa-file"></i> </span></td>
                            <td style="display:none" data-bind="attr:{val:State}" class="state"></td>
                            <td><input type="checkbox" class="icheck" name="checkFile" data-bind="attr:{'data-type':Type,'val':State+'//'+Name}" /></td>
                            <td data-bind="text:Name,click:$parent.clickTd" class="Names"></td>
                            <td data-bind="text:Type,click:$parent.clickTd"></td>
                            <td data-bind="text:date,click:$parent.clickTd"></td>
                            <td data-bind="text:time,click:$parent.clickTd"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
            
        </div>
    </div>
</div>
<div id="AddFolder" class="col-md-12 s modal-example" style="display:none;">
    <div class="modal fade regs">
        <div class="modal-dialog">
            @using (Ajax.BeginForm("AddDirectory", "File",FormMethod.Post, new AjaxOptions { OnSuccess = "OnSuccessDirectory", OnFailure = "errorDec" }, new { @class = "form-signin" }))
            {
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                        <h4 class="modal-title">Добавление каталога</h4>
                    </div>

                    <div class="modal-body">
                        <div class="errors"></div>
                        <div class="panel periodic-login">
                            <div class="panel-body text-center">
                                <div class="form-group form-animate-text editor-label" style="margin-top:40px !important;">
                                    <input type="hidden" name="states" value="" class="inputStateFolder"/>
                                    <input type="text" name="Name" class="form-text inDec" value="" />
                                    <span class="bar"></span>
                                    <label>Имя каталога</label>
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default close-modal" data-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </div><!-- /.modal-content -->
            }
        </div><!-- /.modal-dialog -->
    </div>
</div>
<div id="FileNew" class="col-md-12 s modal-example" style="display:none;">
    <div class="modal fade regs">
        <div class="modal-dialog">
            < <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Загрузка файла</h4>
                </div>

                <div class="modal-body">
                    <div class="errors"></div>
                    <div class="panel periodic-login">
                        <div class="panel-body text-center">
                            <div class="form-group form-animate-text editor-label" style="margin-top:40px !important;">
                                <input type="hidden" name="states" value="" class="inputStateFolder" />
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="input-group fileupload-v1">
                                            <input type="file" name="manualfile" id="uploadFile" class="fileupload-v1-file hidden">
                                            <input type="text" class="form-control fileupload-v1-path" placeholder="File Path..." disabled="">
                                            <span class="input-group-btn">
                                                <button class="btn fileupload-v1-btn" type="button"><i class="fa fa-folder"></i> Choose File</button>
                                            </span>
                                        </div><!-- /input-group -->
                                    </div><!-- /.col-lg-6 -->
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default close-modal" data-dismiss="modal">Закрыть</button>
                    <button type="submit" class="btn btn-primary addFile">Загрузить</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
</div>
<div id="FileUpdate" class="col-md-12 s modal-example" style="display:none;">
    <div class="modal fade regs">
        <div class="modal-dialog">
            < <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h2 class="modal-title" style="    text-align: center;">Заменить файл?</h2>
                </div>
                <div class="modal-footer" style="    text-align: center;">
                    <button type="button" class="btn btn-default close-modal" data-dismiss="modal">Нет</button>
                    <button type="submit" class="btn btn-primary addFile">Да</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
</div>